#!/usr/bin/env python3
"""Copy all Dash_* tables from DigitalOcean MySQL into a Neon/Postgres database.

Usage:
  python EA-SA-Dash/scripts/copy_dash_to_neon.py --database-url "postgresql://..."
  python EA-SA-Dash/scripts/copy_dash_to_neon.py   # reads DATABASE_URL from EA-SA-Dash/.env
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
from country_data_common import connect as mysql_connect

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    sys.stderr.write("Install psycopg:  pip install 'psycopg[binary]'\n")
    raise

TYPE_MAP = [
    (re.compile(r"^tinyint", re.I), "SMALLINT"),
    (re.compile(r"^bigint", re.I), "BIGINT"),
    (re.compile(r"^int", re.I), "INTEGER"),
    (re.compile(r"^mediumint", re.I), "INTEGER"),
    (re.compile(r"^smallint", re.I), "SMALLINT"),
    (re.compile(r"^varchar\((\d+)\)", re.I), lambda m: f"VARCHAR({m.group(1)})"),
    (re.compile(r"^char\((\d+)\)", re.I), lambda m: f"CHAR({m.group(1)})"),
    (re.compile(r"^(medium|long)?text", re.I), "TEXT"),
    (re.compile(r"^datetime", re.I), "TIMESTAMP"),
    (re.compile(r"^timestamp", re.I), "TIMESTAMP"),
    (re.compile(r"^date", re.I), "DATE"),
    (re.compile(r"^decimal\((\d+),(\d+)\)", re.I), lambda m: f"NUMERIC({m.group(1)},{m.group(2)})"),
    (re.compile(r"^float|^double", re.I), "DOUBLE PRECISION"),
    (re.compile(r"^json", re.I), "TEXT"),
]


def pg_type(mysql_type: str) -> str:
    t = mysql_type.strip()
    for pat, repl in TYPE_MAP:
        m = pat.search(t)
        if m:
            return repl(m) if callable(repl) else repl
    return "TEXT"


def qident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def load_database_url(explicit: str | None) -> str:
    if explicit:
        return explicit
    env_path = Path(__file__).resolve().parents[1] / ".env"
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            s = line.strip()
            if s.startswith("DATABASE_URL="):
                return s.split("=", 1)[1].strip().strip('"').strip("'")
            if s.startswith("NEON_DATABASE_URL="):
                return s.split("=", 1)[1].strip().strip('"').strip("'")
    raise SystemExit("Pass --database-url or set DATABASE_URL in EA-SA-Dash/.env")


def create_table(pg_cur, mysql_cur, table: str) -> list[str]:
    mysql_cur.execute(f"DESCRIBE `{table}`")
    cols = mysql_cur.fetchall()
    mysql_cur.execute(f"SHOW INDEX FROM `{table}`")
    indexes = mysql_cur.fetchall()

    col_sql = []
    pk = []
    names = []
    for c in cols:
        name = c["Field"]
        names.append(name)
        extra = (c.get("Extra") or "").lower()
        ident = qident(name)
        typ = pg_type(c["Type"])
        if "auto_increment" in extra:
            typ = "INTEGER GENERATED BY DEFAULT AS IDENTITY" if "int" in c["Type"].lower() else typ + " GENERATED BY DEFAULT AS IDENTITY"
            if c["Type"].lower().startswith("bigint"):
                typ = "BIGINT GENERATED BY DEFAULT AS IDENTITY"
        null = "NULL" if c["Null"] == "YES" else "NOT NULL"
        default = c.get("Default")
        default_sql = ""
        if extra.find("auto_increment") >= 0:
            default_sql = ""
        elif default is not None and str(default).upper() in ("CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP()"):
            default_sql = " DEFAULT CURRENT_TIMESTAMP"
        elif default is not None and str(default).upper() != "NULL":
            if re.match(r"^-?\d+(\.\d+)?$", str(default)):
                default_sql = f" DEFAULT {default}"
            else:
                default_sql = " DEFAULT '" + str(default).replace("'", "''") + "'"
        if (c.get("Key") or "") == "PRI":
            pk.append(ident)
        col_sql.append(f"  {ident} {typ} {null}{default_sql}".rstrip())

    pk_sql = f",\n  PRIMARY KEY ({', '.join(pk)})" if pk else ""
    ddl = f"DROP TABLE IF EXISTS {qident(table)} CASCADE;\nCREATE TABLE {qident(table)} (\n" + ",\n".join(col_sql) + pk_sql + "\n);"
    pg_cur.execute(ddl)

    by_key: dict[str, list] = {}
    for idx in indexes:
        by_key.setdefault(idx["Key_name"], []).append(idx)
    for key, parts in by_key.items():
        if key == "PRIMARY":
            continue
        cols_i = [qident(p["Column_name"]) for p in sorted(parts, key=lambda x: x["Seq_in_index"])]
        uniq = "UNIQUE " if not parts[0]["Non_unique"] else ""
        iname = qident(f"{table}_{key}"[:60])
        pg_cur.execute(f"CREATE {uniq}INDEX {iname} ON {qident(table)} ({', '.join(cols_i)})")
    return names


def copy_table(mysql_cur, pg_cur, table: str, cols: list[str]) -> int:
    mysql_cur.execute(f"SELECT * FROM `{table}`")
    rows = mysql_cur.fetchall()
    if not rows:
        print(f"  {table}: 0 rows")
        return 0
    idents = [qident(c) for c in cols]
    placeholders = ", ".join(["%s"] * len(cols))
    sql = f"INSERT INTO {qident(table)} ({', '.join(idents)}) VALUES ({placeholders})"
    batch = []
    for r in rows:
        batch.append([r.get(c) for c in cols])
        if len(batch) >= 400:
            pg_cur.executemany(sql, batch)
            batch.clear()
    if batch:
        pg_cur.executemany(sql, batch)
    print(f"  {table}: {len(rows)} rows")
    return len(rows)


def reset_identities(pg_cur, mysql_cur, table: str) -> None:
    mysql_cur.execute(f"DESCRIBE `{table}`")
    for c in mysql_cur.fetchall():
        extra = (c.get("Extra") or "").lower()
        if "auto_increment" not in extra:
            continue
        col = c["Field"]
        pg_cur.execute(f"SELECT COALESCE(MAX({qident(col)}), 1) AS m FROM {qident(table)}")
        m = pg_cur.fetchone()["m"]
        if m is None:
            continue
        pg_cur.execute(
            "SELECT pg_get_serial_sequence(%s, %s) AS s",
            (f'"{table}"', col),
        )
        s = pg_cur.fetchone()["s"]
        if s:
            pg_cur.execute("SELECT setval(%s, %s, true)", (s, int(m)))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--database-url")
    args = ap.parse_args()
    url = load_database_url(args.database_url)

    mysql_cn = mysql_connect()
    mysql_cur = mysql_cn.cursor()
    pg_cn = psycopg.connect(url, row_factory=dict_row, sslmode="require")
    pg_cn.autocommit = False
    pg_cur = pg_cn.cursor()

    mysql_cur.execute("SHOW TABLES LIKE 'Dash_%'")
    tables = [list(r.values())[0] for r in mysql_cur.fetchall()]
    tables.sort(key=lambda t: (0 if t == "Dash_all_data" else 1, t))
    print(f"Copying {len(tables)} Dash_* tables -> Neon")
    try:
        for table in tables:
            cols = create_table(pg_cur, mysql_cur, table)
            copy_table(mysql_cur, pg_cur, table, cols)
            reset_identities(pg_cur, mysql_cur, table)
        pg_cn.commit()
        print("Done.")
        return 0
    except Exception:
        pg_cn.rollback()
        raise
    finally:
        mysql_cur.close()
        mysql_cn.close()
        pg_cur.close()
        pg_cn.close()


if __name__ == "__main__":
    raise SystemExit(main())
